# Site settings
title: Pufan Jiang's Blog
SEOTitle: Pufan Jiang | 江浦饭
email: jiangpufan@gmail.com
description: "Pufan Jiang's personal blog."
keyword: "tech | software"
url: "http://otnt.github.io/"           # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# SNS settings
RSS: true
zhihu_username:     jiangpufan
github_username:    otnt
#twitter_username:  huxpro
#facebook_username:  huxpro
linkedin_username: pufanjiang

# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# Disqus settings
disqus_username: pufan-jiangs-blog

# Analytics settings
# Google Analytics
ga_track_id: 'UA-91677434-1'            # Format: UA-xxxxxx-xx
ga_domain: http://otnt.github.io


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Graduated from SJTU and CMU. Currently working at Google."
sidebar-avatar: /img/icon.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
# This is a cool feature but seems useless to me.
featured-tags: false                    # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Plugins
gems: [jekyll-paginate]
